
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
// 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const USER_IMAGE_SUCCESS = "USER_IMAGE_SUCCESS";
export const USER_IMAGE_BASE_URL_SUCCESS = "USER_IMAGE_BASE_URL_SUCCESS";
// 
export const USER_EMAIL_SUCCESS = "USER_EMAIL_SUCCESS";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const GET_USERS = "GET_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const LOADING_USERS = "LOADING_USERS"
export const GET_VERTCALS = "GET_VERTICALS"
export const CREATE_MERCHANT = "CREATE_MERCHANT"
export const CREATE_VERTICAL = "CREATE_VERTICAL"  
export const GET_VERTICALS = "GET_VERTICALS"  
export const LOADING_VERTICALS = "LOADING_VERTICALS" 
export const GET_MERCHANTS = "GET_MERCHANTS" 
export const ADD_CARTEGORY = "ADD_CARTEGORY"
export const ADD_HASHTAG = "ADD_HASHTAG"
export const ADD_HASHTAG_ENTRY = "ADD_HASHTAG_ENTRY"

